#!/bin/bash

usage() {
	cat >&2 << EOF
Usage: $0 FILE [ID]

MANDATORY ARGUMENTS:

FILE	Specify the file to upload. If the file ends in .hxml, it is read to
		find the first '-lua' target, and this file is then uploaded.

OPTIONAL ARGUMENTS:

ID		The id of the computer to which FILE is uploaded. If absent, computer 0
		is used.

ENVIRONMENT VARIABLES:

CRAFTOS_PATH
		Specifies the root of the craftos-pc installation. If undefined, taken
		to be ~/.local/share/craftos-pc
EOF
}

# Parse args
if [[ $# -gt 2 ]]; then
	usage
	exit 1
fi
src=$1
deps=($src)
craftos_pc_id=${2:-0}
craftos_path=${CRAFTOS_PATH:-~/.local/share/craftos-pc}
artifact=""

if [[ "$src" == "" ]]; then
	src=.
fi

if [[ -d "$src" ]]; then
	src=$src/build.hxml
fi

case "$src" in
	*.hxml)
		artifact_basename=$(grep -E -- '^-?-lua' "$src" | head -n1 | cut -d' ' -f2)
		if [[ "$artifact_basename" == "" ]]; then
			usage
			exit 1
		fi
		dir=$(dirname "$src")
		artifact=$dir/$artifact_basename
		;;
	*)
		artifact=$src
		;;
esac

do_upload() {
	install -Dm644 $artifact $craftos_path/computer/$craftos_pc_id/
	echo -en "Last upload: $(date)\r"
}

md5sum_deps() {
	case "$1" in
		*.hxml)
			deps=($(find $(dirname $1) -name '*.hx' | sort))
			;;
		*)
			deps=($1)
			;;
	esac
	md5sum ${deps[@]}
}

export -f md5sum_deps
export -f do_upload
while true; do
	do_upload
	sleep 1
	watch -wegc -n1 "md5sum_deps $src" >/dev/null
done
