#!/bin/bash

set -e

usage() {
	cat >&2 << EOF
Usage: $0 [-u] FILE [ID]

OPTIONS:

-u		Compile, upload and quit

MANDATORY ARGUMENTS:

FILE	The .hxml file of manifest of the project to compile and
		upload. The first '-lua' target specified is uploaded
		into craftos.

OPTIONAL ARGUMENTS:

ID		The id of the computer to which FILE is uploaded. If absent, computer 0
		is used.

ENVIRONMENT VARIABLES:

CRAFTOS_PATH
		Specifies the root of the craftos-pc installation. If undefined, taken
		to be ~/.local/share/craftos-pc
EOF
}

upload_only=0
if [[ "$1" == "-u" ]]; then
	upload_only=1
	shift
fi

# Parse args
if [[ $# -gt 2 ]]; then
	usage
	exit 1
fi
src=$1
deps=($src)
craftos_pc_id=${2:-0}
craftos_path=${CRAFTOS_PATH:-~/.local/share/craftos-pc}
artifact=""

if [[ "$src" == "" ]]; then
	src=.
fi

if [[ -d "$src" ]]; then
	src=$src/build.hxml
fi

if [[ ! -f "$src" ]]; then
	echo "$0: no such file: $src" >&2
	usage
	exit 1
fi

artifact_basename=$(grep -E -- '^-?-lua' "$src" | head -n1 | cut -d' ' -f2)
if [[ "$artifact_basename" == "" ]]; then
	usage
	exit 1
fi
dir=$(dirname "$src")
artifact=$dir/$artifact_basename

do_upload() {
	for d in $craftos_path/computer/**/; do
		install -Dm644 $1 $d
	done

	initial="Last upload: $(date) "
	date_hash_width=$(($(tput cols) - ${#initial}))
	date_hash=$(date | md5sum | cut -d' ' -f1)
	echo -en "$initial${date_hash::$date_hash_width}\r"
}

build() {
	haxe build.hxml || rm -f $artifact_basename
}

for to_remove in "$artifact_basename" startup.lua; do
	rm -f $craftos_path/computer/**/$to_remove
done

if [[ $upload_only -ne 0 ]]; then
	build && do_upload $artifact
	exit
fi

md5sum_deps() {
	md5sum $(find $(dirname $1) -name '*.hx' | sort)
}

craftos &
trap "kill -- $!" INT TERM ERR ILL

cd $dir

export -f md5sum_deps
export -f do_upload
while true; do
	build
	if [[ -f "$artifact_basename" ]]; then
		do_upload $artifact_basename
	fi
	watch -wegc -n1 "md5sum_deps ." >/dev/null
	sleep 1
done

wait
